### ISSUE TITLE
Error on scan

### ISSUE THREAD

**Issue by saelco** [rologr35/media_scanner_scan_file#1]
I got error like this:
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'FutureOr<Map<String, dynamic>>'

How to fix it?

**Comment by rologr35** [comment]
It seems a type error, scan function returns a Future value of a HashMap, not a HashMap, that's why the expected value should be a Future<Map<String, dynamic>>. In order to obtain the Map you must wait for the function because of it's an async function. For example: Map<String, dynamic> result = await MediaScannerScanFile.scanFile(filePath);

**Comment by rologr35** [comment]
These are the keys from returned map:
isSuccess -> bool?
filePath -> String?
errorMessage -> String?

**Comment by saelco** [comment]
I just follows your example but that error appears and I don't know whats wrong.

import 'package:flutter/material.dart';
import 'dart:io';

import 'package:media_scanner_scan_file/media_scanner_scan_file.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    File f = File('/storage/emulated/0/Android/data/myproject/files/qZfasTPHGu5iwFfsQ821c9cqkrXYMLw8ddf13Cnh.jpg');
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Center(
          child: Text('File path: ${_scanFile(f)}\n'),
        ),
      ),
    );
  }
}

Future<String> _scanFile(File f) async{
  final result = await MediaScannerScanFile.scanFile(f.path);
  return result['filePath'];
}

**Comment by XuanTung95** [comment]
Hi dudes,

```
E/flutter (21310): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'FutureOr<Map<String, dynamic>>'
E/flutter (21310): #0      MediaScannerScanFile.scanFile (package:media_scanner_scan_file/media_scanner_scan_file.dart:14:12)
E/flutter (21310): <asynchronous suspension>
E/flutter (21310): #1      FileDownloaderController.downloadFile (package:chat_module/vm/file_downloader_controller.dart:29:20)
E/flutter (21310): <asynchronous suspension>
E/flutter (21310): 
```
Dart throw Exception because `Map<dynamic, dynamic>` is returned but expected is `Map<String, dynamic>`
We need to cast it.

``` dart
  static Future<Map<String, dynamic>> scanFile(String fileUri) async {
    final result = await _channel.invokeMethod('scan', <String, dynamic>{
      'fileUri' : fileUri,
    });
    return result;  ==>  return Map<String, dynamic>.from(result);
  }
```
